let LAYOUT_WORKER_PROTOCOL = {
    INITIALIZE: 1,
    RENDER_NODE: 2,
    APPLY_SIZES: 3,
    ERROR: 4,
    TRANSFORMATIONS: 5
};
LAYOUT_WORKER_PROTOCOL = Object.freeze(LAYOUT_WORKER_PROTOCOL);

export default LAYOUT_WORKER_PROTOCOL;
